#1oYL5X1g configure heroku pipeline on heroku
atlp-rwanda/eagles-phantom-backend pull request #14
Opened 2020-09-24 17:10 UTC by Ally4

#### What does this PR do?

- This PR configure Heroku pipeline on Heroku 

#### Description of Task to be completed?

- Creation of the procfile file

- Edition of the procfile file

- Addition of the start script in package.json

#### How should this be online tested?

- Check the address: `https://phantom-eagles-backend.herokuapp.com` in the browser

#### What are the relevant Trello stories?

- `https://trello.com/c/1oYL5X1g/18-setup-continuous-integration-quality-assurance-pipeline`

2020-09-25 14:35 UTC, Ntwali-Josue approved these changes

2020-09-28 15:16 UTC, Ntwali-Josue approved these changes

2020-09-29 15:25 UTC, Ntwali-Josue approved these changes

2020-10-01 11:56 UTC, Mugema123 approved these changes

2020-10-01 12:59 UTC, TuyizeeAnastase requested changes
the address is working well in browser but first resolve those conflicts.

2020-10-05 09:15 UTC, TuyizeeAnastase approved these changes

2020-10-05 09:32 UTC, merged