Configure the app to use postgres database.
atlp-rwanda/eagles-phantom-backend pull request #17
Opened 2020-09-30 12:08 UTC by TuyizeeAnastase

**What does this PR do?**
Sequelizing postgres database

**Tasks to be completed**
-installing sequelize package and initialize them
-create database 
-migrate and seed the tables
-check if data saved in database

**How can be manually tested?**
-create database test
-npm init
-npm run seed

**What are relavant trello story**
https://trello.com/c/3RYihb3M/17-configure-the-app-to-use-postgres-database

2020-09-30 19:59 UTC, Ntwali-Josue approved these changes

2020-10-01 06:08 UTC, Ntwali-Josue approved these changes

2020-10-01 06:51 UTC, Ntwali-Josue requested changes
solve the conflicts you're having in the files that github is showing you

2020-10-01 07:01 UTC, TuyizeeAnastase commented
yeah, Good resolve those conflicts and trevis error.

2020-10-01 07:34 UTC, Mugema123 reviewed
you can squash and remain with one commit. but first remove those conflicts shown github.

2020-10-01 07:58 UTC, TuyizeeAnastase commented
trevis error checked and conflicts resolved.

2020-10-01 08:09 UTC, Ntwali-Josue commented on .sequelizerc
> +}
add a new line at the end of the file

2020-10-01 08:09 UTC, Ntwali-Josue commented on .vscode/settings.json
> +}
add a new line at the end of the file

2020-10-01 08:09 UTC, Ntwali-Josue commented on database/config/config.js
> +}
add a new line at the end of the file

2020-10-01 08:09 UTC, Ntwali-Josue commented on database/models/user.js
> +};
add a new line at the end of the file

2020-10-01 08:09 UTC, Ntwali-Josue commented on database/migrations/20200922194501-create-user.js
> +};
add a new line at the end of the file

2020-10-01 08:22 UTC, TuyizeeAnastase commented on .sequelizerc
> +}
Done.

2020-10-01 08:22 UTC, TuyizeeAnastase commented on .vscode/settings.json
> +}
Done

2020-10-01 08:22 UTC, TuyizeeAnastase commented on database/config/config.js
> +}
Done.

2020-10-01 08:22 UTC, TuyizeeAnastase commented on database/migrations/20200922194501-create-user.js
> +};
Done

2020-10-01 08:23 UTC, TuyizeeAnastase commented on database/models/user.js
> +};
Done

2020-10-01 08:31 UTC, Mugema123 approved these changes

2020-10-01 08:43 UTC, Ntwali-Josue approved these changes

2020-10-01 08:52 UTC, blaise82 requested changes
remove all seeding files
or any migrations all we need is a database setup

2020-10-01 08:52 UTC, blaise82 commented on test/test.js
> +import seedUser from "../database/seeders/20200922194759-User"
why is this important here?

2020-10-01 09:00 UTC, TuyizeeAnastase commented on test/test.js
> +import seedUser from "../database/seeders/20200922194759-User"
removed

2020-10-01 09:02 UTC, Ally4 approved these changes

2020-10-01 11:13 UTC, Ntwali-Josue approved these changes

2020-10-01 11:17 UTC, blaise82 approved these changes

2020-10-01 11:17 UTC, merged