CRUD operations for routes
atlp-rwanda/eagles-phantom-backend pull request #28
Opened 2020-10-13 10:05 UTC by TuyizeeAnastase

**What does this PR do?**
creating CRUD operations for Routes

**What tasks to be completed?**
-create Routes table in database
-create function controller 
-create APIs

**How can be manually tested?**
-clone this repo if you have not cloned it
-run `npm install`
-run `npm run dev`
-in postman send request `localhost:3020/api/v1/routes `

**Relavant trello story**
https://trello.com/c/sFJutiak/7-crud-operations-for-routes

![CRUS for routes](https://user-images.githubusercontent.com/42033331/95846842-3868cd00-0d4c-11eb-8c1d-797377e2e6cf.jpg)

2020-11-04 04:13 UTC, Ally4 commented
work on the deployment

2020-11-04 04:14 UTC, Ally4 approved these changes

2020-11-05 07:06 UTC, Ntwali-Josue approved these changes

2020-11-05 07:15 UTC, Mugema123 approved these changes

2020-11-05 09:16 UTC, TuyizeeAnastase commented
this PR is not deployed because we have got to the limit of deployed app on Heroku so wait one to be merged i will deploy it.

2020-12-23 14:13 UTC, ceelogre requested changes
Giving an invalid id when patching a route seems to crash the server.
<img width="779" alt="Capture d’écran 2020-12-23 à 15 56 30" src="https://user-images.githubusercontent.com/5022823/103003603-bd851500-4539-11eb-92fb-47172cd8c68e.png">

2020-12-23 14:13 UTC, ceelogre commented on src/controllers/routes.js
> +       return res.status(401).json({message:'No Route with that Id'});
Message not translated.

2020-12-23 14:13 UTC, ceelogre commented on src/controllers/routes.js
> +            return res.status(204).send("Route deleted");
Message is not properly formated.

2020-12-23 14:13 UTC, ceelogre commented on src/controllers/routes.js
> +}
`module.exports` is discouraged in ES Modules.

2020-12-23 14:13 UTC, ceelogre commented on src/test/registration.test.js
>          expect(res.body.message).to.be.a('string');
Is there a possibility to assert the error message now that you know it's a string?

2020-12-23 14:13 UTC, ceelogre commented on src/test/routes.test.js
> +const nonAdminToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJydWNlQGdtYWlsLmNvbSIsInJvbGUiOiJkcml2ZXIiLCJpYXQiOjE2MDMzNzcyNzAsImV4cCI6MTYwMzk4MjA3MH0.UCLiQvmKRhD8_iamHOnjMLgVtxs9Z1e1ixV
Variable seems unused.

2020-12-26 12:33 UTC, ceelogre approved these changes

2020-12-26 12:34 UTC, merged