#O6QG2WdZ Reset the password
atlp-rwanda/eagles-phantom-backend pull request #30
Opened 2020-10-19 15:37 UTC by Ally4

#### What does this PR do?

- This PR reset the password of a user who is in the system

#### Description of Task to be completed?

- create a controller for reset link

- create a validation for reset link

- create a router for reset link

#### How should this be manually tested?

- clone this repo

- run `npm i`

- Create a sendgrid account and it key in the .env

- run `npm run dev`

#### What are the relevant pivotal tracker stories?

- https://trello.com/c/O6QG2WdZ/22-reset-password

2020-10-27 06:14 UTC, Ntwali-Josue commented on src/controllers/userController.js
> +      console.log(`this is the email ------------------${email}----------------------`);
can you remove this console.log line

2020-10-27 14:02 UTC, Ally4 commented on src/controllers/userController.js
> +      console.log(`this is the email ------------------${email}----------------------`);
I removed it

2020-10-28 16:28 UTC, Ntwali-Josue approved these changes

2020-10-29 09:27 UTC, Mugema123 approved these changes

2020-11-05 12:16 UTC, TuyizeeAnastase approved these changes

2020-11-09 08:30 UTC, blaise82 reviewed
- remove the token field from your swagger documentation

2020-11-09 08:35 UTC, blaise82 requested changes
- make sure  that you have users table

2020-11-09 08:35 UTC, blaise82 commented on package.json
> +    "seed": "npx sequelize-cli db:seed:all",
remove npx

2020-11-09 08:39 UTC, blaise82 requested changes

2020-11-09 08:39 UTC, blaise82 commented on src/middleware/isDriverOrOperator.js
> +  if (user.role !== 'operator' && user.role !== 'driver') {
why are you using and?

2020-11-09 09:46 UTC, Ally4 commented on src/middleware/isDriverOrOperator.js
> +  if (user.role !== 'operator' && user.role !== 'driver') {
Because there is NOT EQUAL (!==)

2020-11-09 09:58 UTC, Ally4 commented on package.json
> +    "seed": "npx sequelize-cli db:seed:all",
done

2020-11-09 10:08 UTC, blaise82 approved these changes

2020-11-09 10:08 UTC, merged