ft(updateProfile):update-user-profile-#bL7qBcWY
atlp-rwanda/eagles-phantom-backend pull request #33
Opened 2020-10-27 09:33 UTC by Mugema123

**What does this PR do?**
This PR update Driver or Operator Profile
**Description of Task to be completed?**
creating a controller for a updating driver or operator
Testing the controller
creating a validation for controller

**How should this be manually tested?**
-clone this repo
-run npm i
-Create a sendgrid account and it key in the .env
-run npm run dev
-Get all users
*localhost:3020/api/v1/auth/allusers
-Login as a Driver or Operator
*localhost:3020/api/v1/auth/login
-Update any field
*localhost:3020/api/v1/auth/updateprofile/:id

**What are the relevant pivotal tracker stories?**
#bL7qBcWY
<img width="960" alt="w" src="https://user-images.githubusercontent.com/68016181/97282850-d6c65980-1847-11eb-8550-bb658404ec8b.png">
<img width="960" alt="w1" src="https://user-images.githubusercontent.com/68016181/97282953-f78eaf00-1847-11eb-983e-35c3353be36e.png">
<img width="960" alt="w2" src="https://user-images.githubusercontent.com/68016181/97283015-05443480-1848-11eb-822a-ab534b95db8e.png">

2020-11-03 08:52 UTC, Ally4 commented
That's good Ronald!. I would like to ask you to check on the deployment!.

2020-11-03 19:37 UTC, Ntwali-Josue approved these changes

2020-11-03 19:39 UTC, Ntwali-Josue commented
resolve these conflicts @Mugema123

2020-11-04 04:11 UTC, Ally4 commented
work on the conflict

2020-11-04 04:11 UTC, Ally4 approved these changes

2020-11-04 14:15 UTC, TuyizeeAnastase approved these changes

2020-11-05 10:43 UTC, blaise82 commented
Make sure that it doesn't return admins and password while trying to fetch drivers and operators

2020-11-05 10:51 UTC, blaise82 commented
make sure that a user can't update his email or role

2020-11-05 11:10 UTC, blaise82 requested changes

2020-11-05 11:10 UTC, blaise82 commented on .travis.yml
> +  - psql -c 'CREATE DATABASE test_db;' -U postgres
make sure that only one database creation 
is added to your .Travis.yml file

2020-11-05 11:10 UTC, blaise82 commented on src/controllers/userController.js
> +        user: updatedUser })
you first need to check if the user exists 
then if he does then update the user 
or return 404

2020-11-06 15:17 UTC, blaise82 approved these changes

2020-11-08 06:59 UTC, merged