#WP4NQf2S-ft-assign-driver-to-bus
atlp-rwanda/eagles-phantom-backend pull request #37
Opened 2020-11-12 16:18 UTC by Mugema123

**What does this PR do?**
 PR is for assigning a driver to a bus
**Description of Task to be completed?**

- Operator should be able to assign and unassign a driver to a bus
` localhost:3020/api/v1/assignDriver/:id`
`localhost:3020/api/v1/unassignDriver/:id`
**How should this be manually tested?**

- By using postman (currently)
`login as admin:'email:josh@gmail.com' and 'password:admin'`
`create driver and operator by localhost:3020/api/v1/auth/register`
`Operator can assign or unassign a driver to a bus`
**What are the relevant pivotal tracker stories?**
#WP4NQf2S

**Screenshots (if appropriate)**

<img width="960" alt="final1" src="https://user-images.githubusercontent.com/68016181/98965828-2d53b900-2513-11eb-8dee-02b5c0b3e1c3.png">
<img width="960" alt="final2" src="https://user-images.githubusercontent.com/68016181/98965871-3d6b9880-2513-11eb-9034-ac4a793c6d18.png">

2021-01-05 20:08 UTC, TuyizeeAnastase requested changes
there are two files with the same code and functionalities(duplicated) `userController vs registController` and `busController vs bus.controller`

2021-01-05 20:10 UTC, TuyizeeAnastase commented
i can't login using credentials given in description `login as admin:'email:josh@gmail.com' and 'password:admin'` 
but i used ```
{
    "email":"bruce@gmail.com",
    "password":"Driver"
}
``` and i think you can edit description.

2021-01-07 11:48 UTC, blaise82 requested changes

2021-01-07 11:48 UTC, blaise82 commented on src/database/migrations/20201020051502-create-users.js
> +};
why did you create a new user migration?

2021-01-07 11:48 UTC, blaise82 commented on src/database/migrations/20201013145009-create-bus.js
> +      },
don't directly update the migration file

2021-01-07 11:48 UTC, blaise82 commented on src/database/migrations/20201111141736-create-bus.js
> +};
why do we have to create bus migration files?

2021-01-07 12:38 UTC, Ally4 commented
You have conflicts
Assign bus does not work ("message": "provide valid email")
Unassign bus does not work ("message": "provide valid email")

2021-01-07 13:04 UTC, Ally4 commented
You have conflicts

2021-01-07 13:05 UTC, Ally4 approved these changes

2021-01-08 07:12 UTC, merged