#S24FSo0T Setup dotenv
atlp-rwanda/eagles-phantom-backend pull request #4
Opened 2020-09-23 16:41 UTC by Ally4

#### What does this PR do?
This PR is to setup the dotenv
#### Description of Task to be completed?
Creation of the .env file
Creation of the .env.example file
#### How should this be manually tested? 
By checking the repository once the PR merged
#### Any background context you want to provide?
Installation of the dotenv package
#### What are the relevant Trello stories?
#S24FSo0T

2020-09-24 14:06 UTC, Ntwali-Josue approved these changes

2020-09-24 14:48 UTC, Mugema123 approved these changes

2020-09-30 12:33 UTC, TuyizeeAnastase approved these changes

2020-09-30 13:49 UTC, blaise82 commented
i haven't seen any changes to the packages.json file
which  means that no new package was added. eg: dotenv package

2020-10-05 07:32 UTC, ceelogre requested changes

2020-10-05 07:32 UTC, ceelogre commented on .babelrc
> +    ]
Do you need this after our discussion?

2020-10-05 07:32 UTC, ceelogre commented on package.json
> +    "coverage": "^0.4.1",
`coverage` should not be in dependencies.

2020-10-05 07:34 UTC, Ally4 commented on .babelrc
> +    ]
no

2020-10-05 07:53 UTC, ceelogre approved these changes

2020-10-05 07:53 UTC, merged